### ISSUE TITLE
More High Level of Using Terminologies

### ISSUE THREAD

**Issue by mervinandres** [ModernAppsNinja/CourseFeedback#112]
This is not for me but for some of very new in listening and studying Tanzu Portfolio. Please use a lot of examples rather than discussing the technical terms of of the services and products. It much better to understand if you use some examples that explain how it provide solutions into a lot of challenges. But appreciated this course, it was a good discussion for me since I'm familiar with the product. Thanks!

**Comment by afewell** [comment]
@mervinandres Thanks so much for you feedback, we will keep these in mind as we update the materials. 

Thank you!
