### ISSUE TITLE
Click Through parts of the course only shows at 50%

### ISSUE THREAD

**Issue by charliechocho** [ModernAppsNinja/CourseFeedback#116]
When you get to the click through presentations of the course you need to go full screen in order to show the whole thing. It doesn't work in the embedded mode. There is space to show it embedded as well. Seem to be a formatting problem.

**Comment by afewell** [comment]
@charliechocho thanks for letting us know! We are in the process of moving to a new back-end platform over the next few weeks, which will hopefully correct the issue. 

Thanks!
