### ISSUE TITLE
Great course. A little outdated.

### ISSUE THREAD

**Issue by JeepGuy** [ModernAppsNinja/CourseFeedback#121]
Good Course.

Some of the data is outdated. It caused me to search the web to find out more answers and the updated information - which in effect added to my learning. 

Frequently the presenters dropped their voice volume and rushed through the last one to three words in their sentences making it very hard to understand what the point was. 

THANK YOU for this - it was VERY informative.

**Comment by afewell** [comment]
@JeepGuy Thanks so much for your feedback!
