### ISSUE TITLE
Module 2 HOL link is invalid for me

### ISSUE THREAD

**Issue by scottbri** [ModernAppsNinja/CourseFeedback#124]
Please provide feedback for the course below. Thanks so much for your feedback and contributions!
I believe this is the same issue as the Module 1 HOL link.  I believe the correct link is: http://labs.hol.vmware.com/HOL/catalogs/lab/7811

**Comment by afewell** [comment]
I believe @pegeaton got these fixed and should be working now.

Thanks so much for letting us know @scottbri
