### ISSUE TITLE
500 error when trying to view completion certificate

### ISSUE THREAD

**Issue by scottbri** [ModernAppsNinja/CourseFeedback#128]
Immediately after completing course, i am presented with a link to view certificate of completion.  This link returns a 500

There has been a 500 error on the ModernApps Ninja Learning Platform servers
Please wait a few seconds and then reload the page.

**Comment by afewell** [comment]
@scottbri Thanks so much for letting me know! Our platform hosting service did a major version upgrade recently and I think its created some issues as ive seen several similar ones over the past few days. I am opening a ticket with the service provider now and will update this ticket when I get more info. 

Thank you!

**Comment by afewell** [comment]
@scottbri this issue should be resolved now, thanks again for letting me know!
