### ISSUE TITLE
Would have liked to see more than just administrative pieces

### ISSUE THREAD

**Issue by dantedog29** [ModernAppsNinja/CourseFeedback#26]
I guess you have to start somewhere, however, I would have preferred that the start of this course was more geared towards actual learning than just setting up addition to slack and google groups. Also, can google groups send to non-gmail email addresses?

**Comment by afewellvmware** [comment]
Hi @dantedog29 , thanks for your patience. We have students from a number of different backgrounds, we use to be more aggressive about more technical tasks earlier in the curriculum but have tempered pacing some based on feedback, hoping more advanced users can skim through the materials that are easier for them quickly. As we release the modernapps ninja 201/301/401 courses they will be progressively more technical and with more hands-on exercises. 

Google groups should be able to send to any email address, but I think the address does need to be registered with google. There are some restrictions, for example some VMware employees have company google suite accounts and others dont, and employees who do not have vmware gsuite access cannot use their vmware email address to login to google at all. But aside from any similar caveats, you should in general be able to register any email address with google and use with google groups and should not require any paid tier of service.

Thank you!

**Comment by dantedog29** [comment]
Thank you Art, I appreciate the response. I am looking forward to the ModernAppsNinja 201 course coming out tomorrow and the rest of them. I will, also, take a look at the TMC courses and everything else as well.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
