### ISSUE TITLE
New Courses released on July 3rd allow starting but dont work

### ISSUE THREAD

**Issue by vrabbi** [ModernAppsNinja/CourseFeedback#33]
2 new courses say that they are live on july 3rd but today i tried to start the labs and they allow you to start but nothing shows up and they dont load.

**Comment by afewellvmware** [comment]
Thanks so much for the feedback, I have gotten behind on some release dates but I have adjusted the course start dates and going forward will do more to ensure we dont have to push back any release dates. 

Thanks!
