### ISSUE TITLE
Tanzu Mission Control 201 course link seems to serve 101 content

### ISSUE THREAD

**Issue by wookieeza** [ModernAppsNinja/CourseFeedback#40]
Hi,

I have completed teh 101 course, when I proceed to 201, I seem to be getting content from 101[https://www.modernapps.ninja/courses/course-v1:modernapps+COU-MC3546+Perpetual/course/](url) this is the link directed to for the 201 course

it's 'Welcome to the course' content refers to 101

https://www.modernapps.ninja/courses/course-v1:modernapps+COU-MC3546+Perpetual/courseware/e6b1c184a130479b9f76fe0143437805/8f8323d01cfe4d709b4a6b67b3ccab0d/1?activate_block_id=block-v1%3Amodernapps%2BCOU-MC3546%2BPerpetual%2Btype%40vertical%2Bblock%401cb00ecda2f0464ab01d652169da4e36

**Comment by afewellvmware** [comment]
@wookieeza Thanks so much for pointing this out! I updated the material so it says 201 now. Originally 101 and 201 were one course and I broke it out into 2 courses to increase modularity and missed that, thanks again for letting me know!
