### ISSUE TITLE
Helpful overview

### ISSUE THREAD

**Issue by ecipra** [ModernAppsNinja/CourseFeedback#88]
Found the course to be generally understandable, even for someone in a non-technical role like myself. Appreciated the TMC overview. Would have liked to see a few more demos of the features in action.

**Comment by afewell** [comment]
@ecipra great feedback thanks. I have been meaning to get more demos, originally we intended for the 101/201 course to be a single course but realized it can be useful to have the 101 without labs so we moved labs to the 201 level and instead I have been meaning to put more demos at the 101 level course. I do already have this noted down in another ticket so I will go ahead and close this ticket, but will make these updates as soon as we can. 

Thanks!
