### ISSUE TITLE
Feedback - vSphere with Tanzu 101

### ISSUE THREAD

**Issue by egnidina** [ModernAppsNinja/CourseFeedback#89]
Knowledge Check – TKG - The last questions is empty
Be good to add the text step-by-step guide of installation vSphere with Tanzu (as labs or simulation)
Be good to make difference between vSphere with Taznu with NSX-T and Antrea 
Add simulations for working with kubectl commands
Description of TKG classes (VM classes)

Good courses! Thank you!

**Comment by afewell** [comment]
Hi @egnidina thanks so much for the feedback! We originally planned to make a single course that went more in depth, but we have had requests from some portion of the audience to separate out the high-level intro, so people who want to get the big picture but without as much depth. So we decided to make it a 2 part course with 101 and 201, where the 101 will be more high level and we will get further into details with simulations and hands on labs in the 201. We are already well underway with the 201 and hope to have a preview for the 201 within a couple weeks. I have all the content you suggested scoped for the 201 and will make sure we include everything you list here. I'll send out another notice as soon as we have the 201 course ready. 

Also thanks for pointing out the blank question, I fixed that and I also have a task to add some more questions. 

Thank you!
