### ISSUE TITLE
great course

### ISSUE THREAD

**Issue by ChrisJLittle** [ModernAppsNinja/CourseFeedback#91]
Top-notch as always Art. This is a great primer for anyone that is getting started with vSphere with Tanzu and wants to learn more about how it works and the different deployment methods. I liked that it included bits of TKGI, TKGm and TMC as well to show how this particular product fits in to the whole Tanzu portfolio.

The only issue I found was with the quiz for the Kubernetes review section...there was a question that looked like it was part of a template that should have been removed or updated with a "real" question. I took a screenshot so you can see what I'm talking about.
![kubernetes quiz question](https://user-images.githubusercontent.com/50591431/95279404-e71e8200-080f-11eb-97e3-b67441b1bfcb.png)

**Comment by afewell** [comment]
Thanks so much @ChrisJLittle ! I pulled out the blank question. 

Thanks again!
